let timelineElements = [
	{
		id: 1,
		title: 'Frontend Developer',
		institute: 'Craftsmen Ltd.',
		location: 'Dragontail, Ascana',
		description: [
			'Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
		],
		buttonText: 'View Frontend Projects',
		date: 'August 2016 - present',
		icon: 'work',
	},
	{
		id: 2,
		title: 'Backend Developer',
		institute: 'Craftsmen Ltd.',
		location: 'Skystead, Craonia',
		description: [
			'Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
		],
		buttonText: 'View Backend Projects',
		date: 'June 2013 - August 2016',
		icon: 'work',
	},
	{
		id: 3,
		title: 'Quality Assurance Engineer',
		institute: 'Craftsmen Ltd.',
		location: 'South Warren, Geshington',
		description: [
			'Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
		],
		buttonText: 'Company Website',
		date: 'September 2011 - June 2013',
		icon: 'work',
	},
	{
		id: 4,
		title: 'Oak Ridge College',
		institute: 'Craftsmen Ltd.',
		location: 'South Warren, Geshington',
		description: [
			'Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
		],
		buttonText: 'Course Certificate',
		date: 'September 2011',
		icon: 'school',
	},
	{
		id: 5,
		title: 'Hawking College',
		institute: 'Craftsmen Ltd.',
		location: 'Skystead, Craonia',
		description: [
			'Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
		],
		buttonText: 'College Projects',
		date: '2007 - 2011',
		icon: 'school',
	},
	{
		id: 6,
		title: 'Marble Hills Grammar School',
		institute: 'Craftsmen Ltd.',
		location: 'Dragontail, Ascana',
		description: [
			'Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
			'College - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque sagittis tellus, non ultrices lacus tempus vel.',
		],
		date: '2003 - 2007',
		icon: 'school',
	},
];

export default timelineElements;
