let timelineElements = [
	{
		id: 1,
		title: 'Senior Software Engineer',
		institute: 'Flarie',
		location: 'Stockholm, Sweden',
		description: [
			'Led development of 70% of new product features, including Receipt Scan, User Guidance, Game Wizard, and GDPR compliance, significantly enhancing user experience and regulatory alignment.',
			'Designed and implemented 60% of the serverless architecture for event driven workflows, improving system scalability and performance by 23%.',
			'Contributed to key product decisions and designing of business-critical services.',
			'Assisted in data migration, ensuring a seamless transition while maintaining data integrity. Refactored analyticsdependent services by writing complex, high-throughput queries optimized for big data environments.',
			'Spearheaded efforts to achieve 95% test coverage across the system, with a strong focus on robust authentication and authorization workflows.',
		],
		buttonText: 'Company Website',
		link: 'https://flarie.com/',
		date: 'October 2023 - Present',
		icon: 'work',
	},
	{
		id: 2,
		title: 'Software Development Engineer II',
		institute: 'Fonn Group (7mountains)',
		location: 'Bergen, Norway',
		description: [
			'Developed award-winning cloud news rundown tool named Dina (https://7mountains.com/), recognised at IBC',
			'Building modules for serverless application (AWS SAM).',
			'Developing and maintaining features in micro-services with AWS Lambda, AWS api-gateway, AWS S3, AWS DynamoDB',
			'Developing asset management features in project backend with lambda, DynamoDB, S3, AppSync, CloudFormation, CodePipeline services from AWS.',
			'Works with Apollo Client in React for Client Side',
			'Integrated 35% of third-party features from Mimir (https://mjoll.no/mimir) to enhance product functionality, particularly in asset metadata handling.',
			'Built custom UI libraries and reusable components using Styled Components and Material UI, ensuring design consistency across product modules',
		],
		buttonText: 'Company Website',
		link: 'https://www.7mountains.pro/',
		date: 'August 2021 - September 2023',
		icon: 'work',
	},
	{
		id: 3,
		title: 'Frontend Engineer',
		institute: 'IDARE® Bangladesh Ltd.',
		location: 'Banani, Dhaka',
		description: [
			'Converting large amount of data to a graphical interface, through the use of React, Bootstrap, HTML, CSS, and JavaScript, so that users can view and interact with that data.',
			'Implementing 20% of front-end web application by consuming REST API with REACT and maintaining process-flow by REDUX. ',
			'Translating designs and wireframes into high quality code.',
			'Integrated responsive design and optimized rendering performance across devices, reducing initial load times by over 30%',
			'Streamlined performance monitoring and debugging using tools like Chrome DevTools, Lighthouse, and React Profiler',
		],
		buttonText: 'Company Website',
		link: 'https://idare.io/',
		date: 'February 2019 - July 2021',
		icon: 'work',
	},
	{
		id: 4,
		title: 'Junior Software Engineer',
		institute: 'Golden Harvest Group',
		location: 'Gulshan, Dhaka',
		description: [
			'Maintaining and supporting ERP system. Implementing 100% of Production module of Golden Harvest Foods.',
			'Developing 35% of Employee Provident Fund System (Python, React).',
			'Developing 100% of Automated Email & SMS Service for transactions (Python).',
			'Developing 20% of Loan Management System (Python, React).',
			'Writing SQL queries in Business Intelligence Tool (QlikView).',
		],
		buttonText: 'Company Website',
		link: 'https://www.goldenharvestbd.com/',
		date: 'February 2018 - January 2019',
		icon: 'work',
	},

	{
		id: 5,
		title: 'Online Certificate',
		institute: 'The Hong Kong University of Science and Technology',
		location: 'Clear Water Bay, Hong Kong',
		description: ['Front-End Web UI Frameworks and Tools: Bootstrap 4'],
		buttonText: 'Show Certificate',
		link: 'https://www.coursera.org/account/accomplishments/verify/F2JV8V75BG2V',
		date: 'July  2020',
		icon: 'school',
	},
	{
		id: 6,
		title: 'Online Certificate',
		institute: 'The Hong Kong University of Science and Technology',
		location: 'Clear Water Bay, Hong Kong',
		description: ['Front-End Web Development with React'],
		buttonText: 'Show Certificate',
		link: 'https://www.coursera.org/account/accomplishments/verify/YZRQ96FZDPZ5',
		date: 'August 2020',
		icon: 'school',
	},
	{
		id: 7,
		title: 'Bachelor of Science in CSE',
		institute: 'Ahsanullah University of Science & Technology',
		location: 'Tejgaon, Dhaka',
		description: [
			'Completed my Four year Bachelor Degree',
			'Thesis Paper Publication on IJCA -International Journal of Computer Applications, Topic: Data Mining Techniques for (Network) Intrusion Detection System',
		],
		buttonText: 'University Website',
		link: 'https://www.aust.edu/',
		date: 'September 2016',
		icon: 'school',
	},
];

export default timelineElements;
