let timelineElements = [
	{
		id: 1,
		title: 'Software Development Engineer II',
		institute: 'Craftsmen Ltd.',
		location: 'Baridhara DOHS, Dhaka',
		description: [
			'Building modules for serverless application (AWS SAM).',
			'Developing and maintaining features in micro-services with AWS Lambda, AWS api-gateway, AWS S3, AWS DynamoDB',
			'Developing features in project backend with DynamoDB, S3, AppSync, CloudFormation, CodePipeline, Code build services from AWS.',
			'Works with Apollo Client in React for Client Side',
		],
		buttonText: 'Company Website',
		link: 'https://craftsmenltd.com/',
		date: 'August 2021 - present',
		icon: 'work',
	},
	{
		id: 2,
		title: 'Frontend Engineer',
		institute: 'IDARE® Bangladesh Ltd.',
		location: 'Banani, Dhaka',
		description: [
			'Converting large amount of data to a graphical interface, through the use of React, Bootstrap, HTML, CSS, and JavaScript, so that users can view and interact with that data.',
			'Implementing 20% of front-end web application by consuming REST API with REACT and maintaining process-flow by REDUX. ',
			'Translating designs and wireframes into high quality code.',
		],
		buttonText: 'Company Website',
		link: 'https://idare.io/',
		date: 'April 2020 - August 2021',
		icon: 'work',
	},
	{
		id: 3,
		title: 'Executive, IT',
		institute: 'Golden Harvest Group',
		location: 'Gulshan, Dhaka',
		description: [
			'Maintaining and supporting ERP system. Implementing 100% of Production module of Golden Harvest Foods.',
			'Developing 35% of Employee Provident Fund System (Python, React).',
			'Developing 100% of Automated Email & SMS Service for transactions (Python).',
			'Developing 20% of Loan Management System (Python, React).',
			'Writing SQL queries in Business Intelligence Tool (QlikView).',
		],
		buttonText: 'Company Website',
		link: 'https://www.goldenharvestbd.com/',
		date: 'February 2018 - March 2020',
		icon: 'work',
	},
	{
		id: 4,
		title: 'Bachelor of Science in CSE',
		institute: 'Ahsanullah University of Science & Technology',
		location: 'Tejgaon, Dhaka',
		description: [
			'Completed my Four year Bachelor Degree',
			'Thesis Paper Publication on IJCA -International Journal of Computer Applications, Topic: Data Mining Techniques for (Network) Intrusion Detection System',
		],
		buttonText: 'University Website',
		link: 'https://www.aust.edu/',
		date: 'September 2016',
		icon: 'school',
	},
	{
		id: 5,
		title: 'Higher Secondary Certificate',
		institute: 'Chittagong College',
		location: 'Chittagong',
		description: [
			'Completing Two Year Higher School Education with major Science',
			'Chittagong Board Scholarship',
		],
		buttonText: 'College Website',
		link: 'https://ctgcollege.gov.bd/',
		date: '2009 - 2011',
		icon: 'school',
	},
	{
		id: 6,
		title: 'Secondary School Certificate',
		institute: 'Chittagong Collegiate School',
		location: 'Chittagong',
		description: [
			'Completing High School Education with major Science',
			'Chittagong Board Scholarship',
		],
		date: '2005 - 2009',
		buttonText: 'School Website',
		link: 'https://ctgcs.edu.bd/',
		icon: 'school',
	},
];

export default timelineElements;
